/* Java program listing 6.8 the exception is propagated to the topmost level.*/
import java.io.*;
cpublic class Example11
{
	public static void main(String argv[])
	{
		System.out.println("Inside main(). calling method1()");
		method1();
		}catch(ArithmeticException ae)
		{
			System.out.println("Division by zero, illegal operation");
		}
		System.out.println("End of the Program");
	}
	
	public static void method1()
	{
		System.out.println("Inside method1().calling method2()");
		method2();
		System.out.println("Returning from method1()");
	}
	
	public static void method2()throws ArithmeticException
	{
		System.out.println("Inside method2(). calling method3()");
		method3();
		System.out.println("Returning from method2()");
	}
	
	public static void method3()throw ArithmeticException
	{
		System.out.println(" Inside method3().executing method3()");
	
		int i=1,j=0,k;
		k=i/j;
		System.out.println("Returning from method3()");
	}
}
